### ISSUE TITLE
Nothing happens on click "reset"

### ISSUE THREAD

**Issue by consolem** [adamcoulombe/jquery.customSelect#18]
If my form has a "reset"-button the select does not reset. Please fix

**Comment by adamcoulombe** [comment]
this can be easily done by trapping your form's reset event and triggering an update on the customSelect http://jsfiddle.net/adamco/CCMps/1/

Since this isn't a native select box event, and because I generally consider reset buttons bad practice anyway, I won't be supporting it in the plugin at this time.

**Comment by consolem** [comment]
Thanks a lot. This is working for me.
