### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by onebitrocket** [adamcoulombe/jquery.customSelect#21]
Hi

I'm using jq.validate form my forms.

How do I get the custom select to reflect the '.error' class on my select fields which have the class required?

**Comment by adamcoulombe** [comment]
any time you are using two or more plugins to take control of the same object(s) theres a good chance you are going to have to dive into the documentation and figure out how to put the pieces together... in this case you are going to need to make use of some of the callbacks provided by the validate plugin in order to update our customSelect element with the correct class. eg. http://jsfiddle.net/adamco/RAcKT/
