### ISSUE TITLE
.customSelectOpen class is not removed as desired

### ISSUE THREAD

**Issue by iSimonWeb** [adamcoulombe/jquery.customSelect#29]
I can't manage to rotate up the arrow near my customSelect when <select /> is actually open and rotate down it when <option />s are not visible.
To remove the .customSelectOpen I need to click twice...

**Comment by adamcoulombe** [comment]
This example makes use of the `.customSelectOpen` class:
http://jsfiddle.net/adamco/gL8gk/

Right now when a user clicks and selects an option as normal it should remove the class on `change`.

There could be one of two problems though:
1. If the user opens the select, and then closes it by clicking the select box again without selecting an option. The `.customSelectOpen` doesnt go away until next `blur` or `change` event
2. The user selects the same option again. The select will close and same result as above.

The first scenario is probably fixable since we could make the `customSelectSpan` listen for a click to remove the class.

The second secnario is much trickier since there will be no `change` event or anything to listen for.

**Comment by iSimonWeb** [comment]
You got the point. The fix for the first scenario is perfect.
Anyway you miss a third scenario: The user opens the select, and then closes it by clicking anywhere on the page; on first click the select will close but the `.customSelectOpen` doesn't go away like on first scenario.

p.s. sorry if there are any english mistake, I'm italian and I'm trying to do my best :)
Thank you for the support!

**Comment by iSimonWeb** [comment]
Can't you listen to 'click' on 'document' to .blur() the `<select />`? I suppose that could be a good fix.

**Comment by adamcoulombe** [comment]
Yes, Please check the latest version to see if this solves your issue

patch @ line 108 https://github.com/adamcoulombe/jquery.customSelect/commit/e794b111b094a1688bc5909df39bb3b8f740eb1f#L1R108

**Comment by iSimonWeb** [comment]
Yes man! "click away" scenario solved! :)
What about a listener on `.customSelectInner` to blur the `<select />` if expanded?

**Comment by adamcoulombe** [comment]
Was not necessary.... the document listener solves both scenarios. `customSelectOpen` should go away when you click it but maintain focus. (You do not want to blur the select box when the user clicks it as this would be unexpected behaiour)

**Comment by iSimonWeb** [comment]
Yeah you right, I'm observing that now via Firebug. `.customSelectOpen` go away as desired :)
Thank you so much, happy coding!

**Comment by iSimonWeb** [comment]
Look at these awesome customSelect! http://www.spaghettitours-dev.com/charters
:+1:

**Comment by adamcoulombe** [comment]
@iSimonWeb link did not work, would love to see it though

**Comment by iSimonWeb** [comment]
Lol sry, that's the local address!
Here is the right one http://test.spaghettitours.com/charters

**Comment by adamcoulombe** [comment]
@iSimonWeb fantastic stuff I like the animation you implemented. great idea

**Comment by iSimonWeb** [comment]
Thank you :+1:
