### ISSUE TITLE
Focusin does not show options list

### ISSUE THREAD

**Issue by iSimonWeb** [adamcoulombe/jquery.customSelect#30]
I'm moving through inputs in my form with TAB, when customSelect is focused options list is not showed.

**Comment by adamcoulombe** [comment]
Please post example of what you mean. This plugin uses native select boxes and should behave the exact same as a native select

**Comment by iSimonWeb** [comment]
As you can see in this example http://jsfiddle.net/adamco/gL8gk/ (I've just edited the one you made for the other issue I opened) if you focus the `<input />` and then use TAB to move to the `<select />`, it won't open but it's focused since you can change values with keyboard arrows.

**Comment by adamcoulombe** [comment]
This is not any different than a normal select. Please compare http://jsfiddle.net/adamco/tytk9/

**Comment by iSimonWeb** [comment]
ow...I see...so what about to give the plugin a new feature?

Here are some examples:
https://github.com/fnagel/jquery-ui/wiki/Selectmenu
http://code.google.com/p/expandselect/

Cool plugin anyway man :+1:

**Comment by adamcoulombe** [comment]
Those are great but neither use native browser select boxes since there is no way to open them programmatically. Both of those scripts (and many others) emulate select box functionality using other HTML elements. This can hinder user experience and bloat the plugin and is beyond the intent of what `customSelect` is for
