### ISSUE TITLE
.customSelectOpen class issue

### ISSUE THREAD

**Issue by iSimonWeb** [adamcoulombe/jquery.customSelect#39]
Man, it's always me. I found another bug on css class change.

If you have two or more customSelect in the same page:
e.g. #cSelectA and #cSelectB.
You click on #cSelectA the plugin adds `.customSelectOpen` to it, but then if you click on #cSelectB without closing #cSelectA both the customSelects will have `.customSelectOpen` class.

See example here, `.customSelectOpen` adds a red background.
http://jsfiddle.net/hysHB/74/

**Comment by adamcoulombe** [comment]
I have looked in to this a little. Firefox has some very different behaviour when it comes to blurring an open select box. Applying fixes to support this could get very ugly and may actually be a job maybe for a serperate plugin. At this point, I am actually considering removing support for the open state since it just doesnt seem to be feasible in cross-browser implementations without bloating the plugin a great deal

**Comment by iSimonWeb** [comment]
I think that you can easily check what kind of element the user clicked on 'mouseup':
if it's another .customSelect the plugin blurs the open select and triggers a click event on the closed one.

Am I right dude?

**Comment by adamcoulombe** [comment]
yeah but Firefox doesnt fire a mouseup if you click away onto another select :S

http://jsfiddle.net/hysHB/99/

**Comment by adamcoulombe** [comment]
@iSimonWeb Please take a look at 0.4.1 . We were previously blocking mouseup event propogation which was preventing our document mouseup handler from executing (which prevented the manual `.blur` from happening). So in firefox we first check to see if there are other customSelects open, and if so, we allow the mouseUp to propogate as usual, and just apply a focus. Yikes! I get the feeling though that we havent seen the last of this issue. But this hopefully should solve your problem!

**Comment by iSimonWeb** [comment]
Yes it does! Thank you man. See you next issue :P
