### ISSUE TITLE
Enter key is not submitting changes

### ISSUE THREAD

**Issue by Kamilius** [adamcoulombe/jquery.customSelect#45]
Hi. While i'm focused on other inputs of form, hitting Enter key causes "Submit" key being pressed. But while focusing custom select, it just ignores Enter.
How to force enter for default behavior?
Thanks

**Comment by adamcoulombe** [comment]
Browsers do not natively submit forms when hitting enter on select boxes. Such is a different case for input elements.

See: http://stackoverflow.com/questions/2968693/why-doesnt-hitting-enter-when-a-select-is-focused-submit-the-form

You would need extra javascript to do this, though it would hinder usability since people naturally use the enter button to select an option, rather than submit a form.
