### ISSUE TITLE
selected option setting

### ISSUE THREAD

**Issue by michar11** [adamcoulombe/jquery.customSelect#5]
Hi,
Great plugin.
I have a select that get its values through an AJAX request. 
After it gets new values the selected value remains the same
although that option may not be available anymore.
More over select.val does not make any difference. (It should set the selected value)

Thanks!

**Comment by adamcoulombe** [comment]
You need to call $("select.yourselectbox").change() in your Ajax callback to fire the change event. Then the plugin will respond and update the span.

**Comment by michar11** [comment]
That works. Thanks.
Maybe you could add native support so
existing code wouldn't have to be changed.

**Comment by adamcoulombe** [comment]
It's a good idea but there is no native event to listen for select box content changes to my knowledge other than using DOM mutation events.. Which i understand can be performance intensive and have spotty browser support. The other way would be to set up a timeout the check periodically for content changes. 

You are welcome to take a stab at implementing this. But  to me it seems like a special use case and would be much easier to call the change event manually since you are already doing the work to repopulate the select box anyway.
