### ISSUE TITLE
Tabbing into select field fires focus event twice

### ISSUE THREAD

**Issue by baohouse** [adamcoulombe/jquery.customSelect#67]
My app has binds that executes a function based on the focus event. When you tab from one field into a customSelect field, the focus event gets called twice, first from tabbing into the field, and the second from line 107:

<pre>
.on('keyup', function (e) {
    if(!customSelectSpan.hasClass(getClass('Open'))){
        $select.blur();
        $select.focus();
    }else{
        if(e.which==13||e.which==27){
            changed($select,customSelectSpan);
        }
    }
})
</pre>

I'm guessing this part of the code is used to deal with multiple instances of customSelect?

**Comment by adamcoulombe** [comment]
I believe this is done in order to update the span when you are changing the selected option via the up and down arrows. At least one of the browsers (firefox i think) was failing to fire a change event unless you revoke focus. So this is what I had to do.

There may be another way of doing this (not sure?) but this was the solution I came across at the time.

**Comment by andri** [comment]
This might be causing other problems. Bootstrap tooltips and popovers do not work for select boxes that use customSelect.
