### ISSUE TITLE
menus in responsive design 

### ISSUE THREAD

**Issue by g5604** [adamcoulombe/jquery.customSelect#9]
Hi,

I have a strage problem in that if I resize the browser on my responsive site the hit zone of the select menu is very small - it is fine if I refresh the page. I think this is because it is set to display:none initially ? Is there anyway to avoid this problem? 

thanks,
Gareth

**Comment by adamcoulombe** [comment]
if you are setting it to display:none initially, you should be calling customSelect() when you unhide it instead of on page load

**Comment by adamcoulombe** [comment]
alternatively, don't use CSS to hide it initially... do it with JS after calling custom select, that will avoid the issue altogether.

**html**

``` html
<select class="whateverClass"></select>
```

**js**

``` javascript
$("select.whateverClass").customSelect();
$('.whateverClass').hide();

// later that night...

$('.whateverClass').show();
```

**Comment by g5604** [comment]
Hi,

thank you, I had the same problem with show/hide, but calling customSelect after unhiding did the trick. I used enquire.js to achieve this with my responsive layout: 
 <pre>enquire.register("screen and (max-width: 960px)", function() {
       $('select.styled').customSelect();
    }).listen();
</pre>

**Comment by adamcoulombe** [comment]
Nice stuff!

**Comment by tesshsu** [comment]
I had the same issue since doing with RWD select button, try to use trigger as page load, but never work, I found in js it's define the width with -customSelect width as default, so if the screen load as responsive it will be still keep the same width, my case here is 100px; my case use: `$(window).resize(function () {
   $('#payment-form select').trigger('render');     
});`  
But only work as user change the screen viewport. any solution?

**Comment by caneta** [comment]
@tesshsu the same here...
